//
//  FavoriteListViewController.swift
//  myTunes
//
//  Created by MacOS on 26.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit
import Kingfisher

protocol FavoriteListDisplayLogic: AnyObject{
    func snackBar(message: String)
    func displayFavoriteList(viewModel: FavoriteList.Fetch.ViewModel)
}

final class FavoriteListViewController: UIViewController {
    
    var interactor: FavoriteListBusinessLogic?
    var router: (FavoriteListRoutingLogic & FavoriteListDataPassing)?
    var viewModel: FavoriteList.Fetch.ViewModel?
    var gridFlowLayout = GridFlowLayout()
    var favoritesList : [FavoriteList.Fetch.ViewModel.MyTunes] = []
    
    @IBOutlet weak var typeSegmentController: UISegmentedControl!
    @IBOutlet weak var favoritesCollectionView: UICollectionView!
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup Clean Code Design Pattern
    
    private func setup() {
        let viewController = self
        let interactor = FavoriteListInteractor(worker: FavoriteListWorker())
        let presenter = FavoriteListPresenter()
        let router = FavoriteListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        interactor?.fetchFavoriteList()
        self.title = "Favorites"
        navigationController?.navigationBar.titleTextAttributes = [.foregroundColor: UIColor.systemMint]
        self.navigationController?.navigationBar.tintColor = UIColor.systemMint
        let image = UIImage(named: "delete")
        navigationItem.rightBarButtonItem = UIBarButtonItem(image: image , style: .plain, target: self, action: #selector(removeAll))
        navigationItem.rightBarButtonItem?.imageInsets = UIEdgeInsets(top: 3, left: 3, bottom: -4, right: -3)
        typeSegmentController.selectedSegmentIndex = 0
    }
    
    @objc func removeAll(){
        self.interactor?.removeFavoriteList()
        self.interactor?.fetchFavoriteList()
        let alertAction = UIAlertAction(title: "OK", style: .default) { UIAlertAction in
            self.router?.popOver()
        }
        Alert.alertAction(title: "Clean", message: "Removed Favorite List ", action: alertAction)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.fetchFavoriteList()
        registerCollectionView()
    }
    
    
    func registerCollectionView(){
        favoritesCollectionView.collectionViewLayout = gridFlowLayout
        let nibTr = UINib(nibName: "TrackCollectionViewCell", bundle: nil)
        favoritesCollectionView.register(nibTr, forCellWithReuseIdentifier: "trackCell")
        let nibCl = UINib(nibName: "CollectionCollectionViewCell", bundle: nil)
        favoritesCollectionView.register(nibCl, forCellWithReuseIdentifier: "collectionCell")
        let nibAr = UINib(nibName: "ArtistCollectionViewCell", bundle: nil)
        favoritesCollectionView.register(nibAr, forCellWithReuseIdentifier: "artistCell")
    }
    
    @IBAction func typeSegmentedController(_ sender: UISegmentedControl) {
        if self.viewModel?.favoriteList != nil{
            switch sender.selectedSegmentIndex{
            case 0:
                self.favoritesList = (self.viewModel?.favoriteList)!
                self.favoritesCollectionView.reloadData()
                
            case 1:
                self.favoritesList = (self.viewModel?.favoriteList)!
                var filteredData = [FavoriteList.Fetch.ViewModel.MyTunes]()
                for tunes in (self.favoritesList) {
                    let wrapperType = tunes.wrapperType
                    if wrapperType!.contains(WrapperType.track.rawValue){
                        filteredData.append(tunes)
                    }
                }
                self.favoritesList.removeAll()
                self.favoritesList.append(contentsOf: filteredData)
                self.favoritesCollectionView.reloadData()
                
            case 2:
                self.favoritesList = (self.viewModel?.favoriteList)!
                var filteredData = [FavoriteList.Fetch.ViewModel.MyTunes]()
                for tunes in (self.favoritesList) {
                    let wrapperType = tunes.wrapperType
                    if wrapperType!.contains(WrapperType.artist.rawValue){
                        filteredData.append(tunes)
                    }
                }
                self.favoritesList.removeAll()
                self.favoritesList.append(contentsOf: filteredData)
                self.favoritesCollectionView.reloadData()
                
            case 3:
                self.favoritesList = (self.viewModel?.favoriteList)!
                var filteredData = [FavoriteList.Fetch.ViewModel.MyTunes]()
                for tunes in (self.favoritesList) {
                    let wrapperType = tunes.wrapperType
                    if wrapperType!.contains(WrapperType.collection.rawValue){
                        filteredData.append(tunes)
                    }
                }
                self.favoritesList.removeAll()
                self.favoritesList.append(contentsOf: filteredData)
                self.favoritesCollectionView.reloadData()
                
            default:
                break
            }
        }else {
            
        }
    }
    
}

// MARK: - Display view model from City List Presenter

extension FavoriteListViewController : FavoriteListDisplayLogic{
    func snackBar(message: String) {
        AppSnackBar.make(in: self.view, message: message, duration: .custom(1.0)).show()
    }
    func displayFavoriteList(viewModel: FavoriteList.Fetch.ViewModel) {
        self.viewModel = viewModel
        self.favoritesList = viewModel.favoriteList
        favoritesCollectionView.reloadData()
    }
}

extension FavoriteListViewController: UICollectionViewDataSource , UICollectionViewDelegate {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return favoritesList.count ?? 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let trackCell = collectionView.dequeueReusableCell(withReuseIdentifier: "trackCell", for: indexPath) as! TrackCollectionViewCell? else {return UICollectionViewCell()}
        guard let collectionCell = collectionView.dequeueReusableCell(withReuseIdentifier: "collectionCell", for: indexPath) as! CollectionCollectionViewCell? else {return UICollectionViewCell()}
        guard let artistCell = collectionView.dequeueReusableCell(withReuseIdentifier: "artistCell", for: indexPath) as! ArtistCollectionViewCell? else {return UICollectionViewCell()}
        
        let model = self.favoritesList[indexPath.item]
        
        switch model.wrapperType {
            
        case WrapperType.track.rawValue:
            trackCell.configureFavorites(model: model)
            trackCell.favoriteButton.addTapGesture { [unowned self] in
                if typeSegmentController.selectedSegmentIndex == 0{
                self.remove(index: indexPath.row)
                }
            }
            return trackCell
            
        case WrapperType.artist.rawValue:
            artistCell.configureFavorites(model: model)
            artistCell.favoriteButton.addTapGesture { [unowned self] in
                if typeSegmentController.selectedSegmentIndex == 0{
                self.remove(index: indexPath.row)
                }
            }
            return artistCell
            
        case WrapperType.collection.rawValue:
            collectionCell.configureFavorites(model: model)
            collectionCell.favoriteButton.addTapGesture { [unowned self] in
                if typeSegmentController.selectedSegmentIndex == 0{
                self.remove(index: indexPath.row)
                }
            }
            return collectionCell
            
        default:
            return trackCell
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        router?.routeToDetails(index: indexPath.item)
    }
    
    func remove(index: Int){
        self.favoritesList.remove(at: index)
        self.interactor?.removeFavorite(index: index)
        favoritesCollectionView.reloadData()
        self.typeSegmentController.selectedSegmentIndex = 0
    }
}
