//
//  FavoriteListInteractor.swift
//  myTunes
//
//  Created by MacOS on 26.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

protocol FavoriteListBusinessLogic: AnyObject {
    
}

protocol FavoriteListDataStore: AnyObject {
    var favoriteList:[Tunes]? { get set }
}

final class FavoriteListInteractor: FavoriteListBusinessLogic, FavoriteListDataStore{
    var favoriteList: [Tunes]?
    var presenter: FavoriteListPresentationLogic?
    var worker: FavoriteListWorkingLogic?
 
    init(worker: FavoriteListWorkingLogic) {
        self.worker = worker
    }
}
