//
//  FavoriteListPresenter.swift
//  myTunes
//
//  Created by MacOS on 26.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

protocol FavoriteListPresentationLogic: AnyObject {
    func presentFavoriteList(response: FavoriteList.Fetch.Response)
    func presentAlert(title: String , message: String)
    func presentAlertAction(title: String , message: String , action: UIAlertAction)
}

final class FavoriteListPresenter: FavoriteListPresentationLogic {
    
    weak var viewController: FavoriteListDisplayLogic?
   
    func presentFavoriteList(response: FavoriteList.Fetch.Response) {
       
    }
    
    func presentAlert(title: String , message: String){
        Alert.alert(title: title , message: message)
    }
    
    func presentAlertAction(title: String , message: String , action: UIAlertAction) {
        Alert.alertAction(title: title, message: message, action: action)
    }
}


