//
//  MyTunesDetailsPresenter.swift
//  myTunes
//
//  Created by MacOS on 24.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyTunesDetailsPresentationLogic {
    func presentSomething(response: MyTunesDetails.Something.Response)
}

class MyTunesDetailsPresenter: MyTunesDetailsPresentationLogic {
    weak var viewController: MyTunesDetailsDisplayLogic?

    // MARK: Parse and calc respnse from MyTunesDetailsInteractor and send simple view model to MyTunesDetailsViewController to be displayed

    func presentSomething(response: MyTunesDetails.Something.Response) {
        let viewModel = MyTunesDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: MyTunesDetails.SomethingElse.Response) {
//        let viewModel = MyTunesDetails.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
