//
//  MyTunesDetailsInteractor.swift
//  myTunes
//
//  Created by MacOS on 24.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyTunesDetailsBusinessLogic {
    func doSomething(request: MyTunesDetails.Something.Request)
//    func doSomethingElse(request: MyTunesDetails.SomethingElse.Request)
}

protocol MyTunesDetailsDataStore {
    //var name: String { get set }
}

class MyTunesDetailsInteractor: MyTunesDetailsBusinessLogic, MyTunesDetailsDataStore {
    var presenter: MyTunesDetailsPresentationLogic?
    var worker: MyTunesDetailsWorker?
    //var name: String = ""

    // MARK: Do something (and send response to MyTunesDetailsPresenter)

    func doSomething(request: MyTunesDetails.Something.Request) {
        worker = MyTunesDetailsWorker()
        worker?.doSomeWork()

        let response = MyTunesDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: MyTunesDetails.SomethingElse.Request) {
//        worker = MyTunesDetailsWorker()
//        worker?.doSomeOtherWork()
//
//        let response = MyTunesDetails.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
