//
//  MyTunesDetailsInteractor.swift
//  myTunes
//
//  Created by MacOS on 24.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//



protocol MyTunesDetailsBusinessLogic: AnyObject {
    func fetchMyTunesDetails()
    func addTuneToFavorites()
    func fetchTunesList()
}

protocol MyTunesDetailsDataStore:AnyObject {
    var myTune: Results? { get set }
    var tune: Tunes? { get set }
}

final class MyTunesDetailsInteractor: MyTunesDetailsBusinessLogic, MyTunesDetailsDataStore {
    var tune: Tunes?
    var myTune: Results?
    var tunes : [Tunes] = []
    var presenter: MyTunesDetailsPresentationLogic?
    var worker: MyTunesDetailsWorkingLogic?
    
    init(worker: MyTunesDetailsWorkingLogic) {
        self.worker = worker
    }
    
    func fetchTuneFromFavorite(){
        fetchTunesList()
    
    }
    
    func fetchMyTunesDetails() {
        self.presenter?.presentMyTunesDetails(response: .init(tune: tune))
        self.presenter?.presentMyTunesDetails(response:.init(myTune: myTune))
    }
    
    func fetchTunesList() {
        worker?.getFavoriteTunesList() { [weak self] result in
            switch result {
            case .success(let response):
                self?.tunes = response
            case .failure(let error):
                print("error: ", error)
            }
        }
    }
    
    func addTuneToFavorites() {
        if myTune == nil {
            presenter?.shakeView()
            presenter?.alert(message:  "Already Favorited" , title: "Wait a Second")
            
        }else{
        fetchTunesList()
        switch myTune?.wrapperType{
            
        case WrapperType.track.rawValue:
            
            if  tunes.contains(where: {$0.trackId == Int16(truncatingIfNeeded: (myTune?.trackId)!) }){
                presenter?.shakeView()
                presenter?.alert(message:  "\(String(describing: myTune?.trackName ?? "")) is already favorited" , title: "Wait a Second")
                
            }else{
                addTune()
                presenter?.snackBar(message: "\(String(describing: myTune?.trackName ?? ""))")
            }
            
        case WrapperType.collection.rawValue:
            
            if tunes.contains(where: {$0.collectionId == Int16(truncatingIfNeeded:(myTune?.collectionId)!) }){
                presenter?.shakeView()
                presenter?.alert(message:  "\(String(describing: myTune?.collectionName ?? ""))  is already favorited", title: "Wait a Second")
                
            }else{
                addTune()
                presenter?.snackBar(message: "\(String(describing: myTune?.collectionName ?? ""))")
            }
            
        case WrapperType.artist.rawValue:
            
            if tunes.contains(where: {$0.artistId == Int16(truncatingIfNeeded:(myTune?.artistId)!) }){
                presenter?.shakeView()
                presenter?.alert(message:  "\(String(describing: myTune?.artistName ?? ""))  is already favorited" , title: "Wait a Second")
            }else{
                addTune()
                presenter?.snackBar(message: "\(String(describing: myTune?.artistName ?? ""))")
            }
            
        default:
            break
        }
    }
    }
    
    func addTune(){
        worker?.addTune(wrapperType: myTune?.wrapperType, artistId : Int16(truncatingIfNeeded: myTune?.artistId ?? 0) , collectionId : Int16(truncatingIfNeeded: myTune?.collectionId ?? 0) , trackId : Int16(truncatingIfNeeded: myTune?.trackId ?? 0) ,  kind: myTune?.kind, artistName: myTune?.artistName, collectionName: myTune?.collectionName, trackName: myTune?.trackName, artworkUrl100: myTune?.artworkUrl100, releaseDate: myTune?.releaseDate, country: myTune?.country, primaryGenreName: myTune?.primaryGenreName, artistViewUrl: myTune?.artistViewUrl, collectionViewUrl: myTune?.collectionViewUrl, trackViewUrl: myTune?.trackViewUrl)
    }
}
