//
//  MyTunesListModels.swift
//  myTunes
//
//  Created by MacOS on 23.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MyTunesList
{
    // MARK: Use cases

    enum Fetch
    {
    
        struct Response
        {
            var myTunesList: [Results]
        }

        struct ViewModel
        {
            var myTunesList: [MyTunesList.Fetch.ViewModel.MyTunes]
            
            struct MyTunes {
                
            let wrapperType : String?
            let kind : String?
            let artistId : Int?
            let artistName : String?
            let collectionName : String?
            let trackName : String?
            let artworkUrl30 : String?
            let artworkUrl60 : String?
            let artworkUrl100 : String?
            let releaseDate : String?
            let country : String?
            let primaryGenreName : String?
            
                
            }
        }
    }
}
