//
//  MyTunesListPresenter.swift
//  myTunes
//
//  Created by MacOS on 23.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyTunesListPresentationLogic {
    func presentSomething(response: MyTunesList.Something.Response)
}

class MyTunesListPresenter: MyTunesListPresentationLogic {
    weak var viewController: MyTunesListDisplayLogic?

    // MARK: Parse and calc respnse from MyTunesListInteractor and send simple view model to MyTunesListViewController to be displayed

    func presentSomething(response: MyTunesList.Something.Response) {
        let viewModel = MyTunesList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: MyTunesList.SomethingElse.Response) {
//        let viewModel = MyTunesList.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
