//
//  MyTunesListPresenter.swift
//  myTunes
//
//  Created by MacOS on 23.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyTunesListPresentationLogic: AnyObject {
    func presentMyTunesList(response: MyTunesList.Fetch.Response)
}

final class MyTunesListPresenter: MyTunesListPresentationLogic {
    weak var viewController: MyTunesListDisplayLogic?
    
    func presentMyTunesList(response: MyTunesList.Fetch.Response) {
        var myTunesList: [MyTunesList.Fetch.ViewModel.MyTunes] = []
        response.myTunesList.forEach {
            myTunesList.append(MyTunesList.Fetch.ViewModel.MyTunes(wrapperType: $0.wrapperType, kind: $0.kind, artistId: $0.artistId, collectionId: $0.collectionId, trackId: $0.trackId, artistName: $0.artistName, collectionName: $0.collectionName, trackName: $0.trackName, artworkUrl30: $0.artworkUrl30, artworkUrl60: $0.artworkUrl60, artworkUrl100: $0.artworkUrl100, releaseDate: $0.releaseDate, country: $0.country, primaryGenreName: $0.primaryGenreName , artistViewUrl: $0.artistViewUrl, collectionViewUrl: $0.collectionViewUrl , trackViewUrl: $0.trackViewUrl ))
        }

        viewController?.displayMyTunes(viewModel: MyTunesList.Fetch.ViewModel(myTunesList: myTunesList))
    }
}
