//
//  MyTunesListInteractor.swift
//  myTunes
//
//  Created by MacOS on 23.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyTunesListBusinessLogic {
    func doSomething(request: MyTunesList.Something.Request)
//    func doSomethingElse(request: MyTunesList.SomethingElse.Request)
}

protocol MyTunesListDataStore {
    //var name: String { get set }
}

class MyTunesListInteractor: MyTunesListBusinessLogic, MyTunesListDataStore {
    var presenter: MyTunesListPresentationLogic?
    var worker: MyTunesListWorker?
    //var name: String = ""

    // MARK: Do something (and send response to MyTunesListPresenter)

    func doSomething(request: MyTunesList.Something.Request) {
        worker = MyTunesListWorker()
        worker?.doSomeWork()

        let response = MyTunesList.Something.Response()
        presenter?.presentSomething(response: response)
    }
//
//    func doSomethingElse(request: MyTunesList.SomethingElse.Request) {
//        worker = MyTunesListWorker()
//        worker?.doSomeOtherWork()
//
//        let response = MyTunesList.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
